<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\InsuranceCompany;
use Ramsey\Uuid\Uuid;

class InsuranceCompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $insuranceCompanies = [
            [
                'insurance_company_name' => 'Clear Insurance',
                'address' => '',
                'phone' => '(000) 000-0000',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Pekin Insurance',
                'address' => '',
                'phone' => '(888) 735-4611',
                'email' => 'claims@pekininsurance.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Openly',
                'address' => '',
                'phone' => '(888) 808-4842',
                'email' => 'Claims@openly.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Plymouth Rock Assurance',
                'address' => '',
                'phone' => '(844) 242-3555',
                'email' => 'rockcare@plymouthrock.com',
                'website' => 'https://www.plymouthrock.com/',
            ],
            [
                'insurance_company_name' => 'American Family Insurance',
                'address' => '',
                'phone' => '(800) 692-6326',
                'email' => 'Claimdocuments@asics.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Kemper Insurance',
                'address' => '',
                'phone' => '(800) 353-6737',
                'email' => 'Mail.claims@kemper.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Narrangansett Bay Insurance Company',
                'address' => '',
                'phone' => '(800) 343-3375',
                'email' => 'CALLandASK@insurancecompany.com',
                'website' => 'www.nbic.com',
            ],
            [
                'insurance_company_name' => 'State Farm Lloyds',
                'address' => '',
                'phone' => '(800) 732-5246',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'State Farm Fire and Casualty Company',
                'address' => '',
                'phone' => '(845) 226-5005',
                'email' => 'statefarmfireclaims@statefarm.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'First Community Insurance Company',
                'address' => '',
                'phone' => '(866) 401-1106',
                'email' => 'consultar@eugenia',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'New London County Mutual Insurance Company',
                'address' => '',
                'phone' => '(800) 962-0800',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Roadrunner Indemnity Company',
                'address' => '',
                'phone' => '(866) 522-0361',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'AAA Texas',
                'address' => '',
                'phone' => '(180) 067-2524',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'MESA UNDERWRITERS SPECIALTY INSURANCE COMPANY',
                'address' => '',
                'phone' => '(866) 547-0868',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'American Mobile Insurance Exchange',
                'address' => '',
                'phone' => '(844) 631-7819',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Utica National Insurance Group',
                'address' => '',
                'phone' => '(800) 598-8422',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Merrimack Mutual Fire Insurance Company',
                'address' => '',
                'phone' => '(978) 475-3300',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'American Automobile Association',
                'address' => '',
                'phone' => '(800) 222-4357',
                'email' => '',
                'website' => 'https://www.aaa.com/',
            ],
            [
                'insurance_company_name' => 'American Commerce Insurance Company',
                'address' => '',
                'phone' => '(877) 627-3731',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'National Summit Insurance Company',
                'address' => '',
                'phone' => '(800) 749-6419',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Bunker Hill Insurance Company',
                'address' => '',
                'phone' => '(888) 472-5246',
                'email' => '',
                'website' => 'bunkerhillins.com',
            ],
            [
                'insurance_company_name' => 'The Providence Mutual Fire Insurance Company',
                'address' => '',
                'phone' => '(877) 763-1800',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'UNITED STATES LIABILITY INSURANCE COMPANY',
                'address' => '',
                'phone' => '(888) 523-5545',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Rockford Mutual Insurance Company',
                'address' => '',
                'phone' => '(800) 747-7642',
                'email' => 'claims@rockfordmutual.com',
                'website' => 'https://www.rockfordmutual.com/insurance/home',
            ],
            [
                'insurance_company_name' => 'CHASE',
                'address' => '',
                'phone' => '(877) 530-8951',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Church Mutual Insurance Company',
                'address' => '',
                'phone' => '(800) 554-2642',
                'email' => 'claims@churchmutual.com',
                'website' => 'https://www.churchmutual.com/7/Contact-Us',
            ],
            [
                'insurance_company_name' => 'Conifer Insurance Company',
                'address' => '',
                'phone' => '(877) 263-6468',
                'email' => 'claims@coniferinsurance.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'NatGen Premier',
                'address' => '',
                'phone' => '(184) 428-7223',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Underwriters at lloyd´s of london',
                'address' => '',
                'phone' => '(034) 530-0000',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Next',
                'address' => '',
                'phone' => '(800) 252-3439',
                'email' => 'ConsumerProtection@tdi.texas.gov',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'The Hanover Insurance Group',
                'address' => '',
                'phone' => '(800) 628-0250',
                'email' => 'firstreport@hanover.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Ussa Casualty Insurance Company',
                'address' => '',
                'phone' => '(210) 531-8722',
                'email' => '',
                'website' => 'https://www.usaa.com/?wa_ref=pub_global_home',
            ],
            [
                'insurance_company_name' => 'Kingstone Insurance',
                'address' => '',
                'phone' => '(800) 364-7045',
                'email' => 'claimreports@kingstoneic.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Texas Farm Bureau Insurance',
                'address' => '',
                'phone' => '(800) 224-7936',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'American Mercury Lloyds Insurance',
                'address' => '',
                'phone' => '(888) 637-2176',
                'email' => 'wrhome@mercuryinsurance.com',
                'website' => 'www.mercuryinsurance.com',
            ],
            [
                'insurance_company_name' => 'Standard Guaranty Insurance Company',
                'address' => '',
                'phone' => '(800) 652-1262',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'slide insurance company',
                'address' => '',
                'phone' => '(800) 748-2030',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Spinnaker Insurance Company',
                'address' => '',
                'phone' => '(888) 221-7742',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'VYRD Insurance Company',
                'address' => '',
                'phone' => '(844) 217-6993',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Andover',
                'address' => '',
                'phone' => '(203) 744-2800',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Branch Insurance exchange',
                'address' => '',
                'phone' => '(833) 427-2624',
                'email' => '',
                'website' => 'https://www.ourbranch.com/',
            ],
            [
                'insurance_company_name' => 'American Integrity',
                'address' => '',
                'phone' => '(866) 968-8390',
                'email' => 'claimsmail@aiiflorida.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'TypTap Insurance Company',
                'address' => '',
                'phone' => '(844) 289-7968',
                'email' => 'claims@typtap.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'National Summit',
                'address' => '',
                'phone' => '(800) 749-6419',
                'email' => 'claims@natlloyds.com',
                'website' => 'https://www.nationallloydsinsurance.com/',
            ],
            [
                'insurance_company_name' => 'Bass Underwriters',
                'address' => '',
                'phone' => '(954) 316-3198',
                'email' => 'Claims@bassuw.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Sage Sure',
                'address' => '',
                'phone' => '(888) 316-0540',
                'email' => 'claimshelp@sagesure.com',
                'website' => 'https://www.sagesure.com/',
            ],
            [
                'insurance_company_name' => 'Weston Specialty Insurance',
                'address' => '',
                'phone' => '(000) 000-0000',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Homeowners of America insurance Company',
                'address' => '',
                'phone' => '(866) 407-9896',
                'email' => 'claims@hoaic.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Foremost Lloyds of Texas',
                'address' => '',
                'phone' => '(616) 942-3000',
                'email' => 'myclaim@foremost.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Southern Vanguard Insurance Company',
                'address' => '',
                'phone' => '(888) 432-9393',
                'email' => 'rhpclaims@rhpga.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Allied Trust',
                'address' => '',
                'phone' => '(844) 200-2842',
                'email' => 'alliedclaims@transcynd.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Preatorian Insurance Company',
                'address' => '',
                'phone' => '(866) 318-2016',
                'email' => 'claimmail@us.qbe.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Zurich American Insurance Company',
                'address' => '',
                'phone' => '(877) 777-6440',
                'email' => 'sstone@acmclaims.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Colonial Lloyds',
                'address' => '',
                'phone' => '(866) 522-0361',
                'email' => '',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Progressive Homesite',
                'address' => '',
                'phone' => '(800) 466-3748',
                'email' => 'claimdocuments@afics.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'SafeCo Insurance',
                'address' => '',
                'phone' => '(800) 332-3226',
                'email' => 'imaging@libertymutual.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Wellington Insurance Group',
                'address' => '',
                'phone' => '(800) 880-0474',
                'email' => 'claims@wellingtoninsgroup.com',
                'website' => 'http://www.wellingtoninsgroup.com/',
            ],
            [
                'insurance_company_name' => 'Berkshire Hathaway Guard',
                'address' => '',
                'phone' => '(800) 673-2465',
                'email' => 'claims@guard.com',
                'website' => '',
            ],
            [
                'insurance_company_name' => 'Citizens',
                'address' => '',
                'phone' => '(866) 411-2742',
                'email' => 'claims.communications@citizensfla.com',
                'website' => 'www.citizensfla.com',
            ],
            [
                'insurance_company_name' => 'Progressive Insurance',
                'address' => '6300 Wilson Mills Road, Mayfield Village, Ohio 4414',
                'phone' => '866 407 4844',
                'email' => '',
                'website' => 'https://www.progressive.com/',
            ],
            [
                'insurance_company_name' => 'Other Not Mentioned Force Placed Policies',
                'address' => '',
                'phone' => '',
                'email' => '',
                'website' => '',
            ],
        ];

        foreach ($insuranceCompanies as $company) {
            InsuranceCompany::create([
                'uuid' => Uuid::uuid4()->toString(),
                'insurance_company_name' => $company['insurance_company_name'],
                'address' => $company['address'],
                'phone' => $company['phone'],
                'email' => $company['email'],
                'website' => $company['website'],
                'user_id' => 1,
            ]);
        }
    }
}