<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Facades\DB;
use Ramsey\Uuid\Uuid;
class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
{
    $products = [
       
    ['product_name' => 'Dehumidifier (per 24 hour period) Large - No monitoring', 'price' => 190, 'unit' => 'UND', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Closet Understairs', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Bedroom Closet 4', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'BEDROOM 4', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => ''],
    ['product_name' => 'Bedroom Closet 3', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Bedroom Closet 2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Guest Bathroom 2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Master Bedroom 2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Breakfast Area', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Landing', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Master Bedroom Toilet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => ''],
    ['product_name' => 'A/C Room - Toilet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Closet Master Bathroom', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Storage Rental Tax', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Guest Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'A/C ROOM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'LEVEL 2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Utility Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Bathroom Hallway', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Tenant Bathroom', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Hallway Laundry', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Family Room ( Level 2)', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Walk-in Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],

    ['product_name' => 'Open to below', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Guest Room Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Family Room Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Hallway 2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Hallway 1', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Half Bathroom', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Open to Stairs', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Gym Room Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
   
   
    ['product_name' => 'Bedroom 3 Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Closet Guest Bedroom', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Closet Great Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Great Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Girls Guest Bedroom Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Girls Guest Bedroom', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Gym Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Guest living', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Play room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Storage room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Boy Bedroom Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Boy Bedroom', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Girl Bedroom Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Guest Bedroom Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Hallway Bedroom Closet 2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Hallway Bedroom Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Hallway Bedroom', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Dining room Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Pantry 2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Pantry', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Master Bedroom Closet 3', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Master Bedroom Closet 2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Girl Bedroom', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'BATHROOM (2 LEVEL)', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Attic Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Attic 3', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'attic 2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Attic 1', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Master bathroom closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Study', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Garage Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Storege', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Porch', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'TERRACE', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Basement Laundry', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Kitchen 4', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Small Living', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'LIVING ROOM HALLWAY', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Living Room / Kitchen / Dining Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Master dining room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Bathroom closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Blue Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Furnace Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    
    
    ['product_name' => 'Bedroom Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    
    ['product_name' => 'Master Bedroom Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    
    
    ['product_name' => 'temporary heater- propane (per day)', 'price' => 75.26, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    
    ['product_name' => 'Floor prep (Scrape rubber back residue)', 'price' => 50.74, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    
    ['product_name' => 'Repairing and Correcting 9 Foundations Include Permisions, Include Cleaning, Include Debris and Removal', 'price' => 8500, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'ENTRANCE 2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'TV Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Laders 2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Laders', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Entrance closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Work room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Master Shower', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Master bathtub', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Window screen', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Living Room (Level 2)', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Master Storage Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Guest Bedroom', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Office closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Exterior Walls', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Stairs2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Stairs1', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Stairs', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Stairway', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    
    
    ['product_name' => 'Hallway Entrance', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'BAR', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'Living 2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    
    ['product_name' => 'Hallway Master Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Bedroom 1', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Master Toilet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Master TV Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Master Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Fitness Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Hallway Up Stairs', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Debris Removal Tax', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'ROOM 3', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Debris Removal Tax', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Kids Room Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Kids Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Master Hallway Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Master Hallway', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Storage Rental Tax', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Hallway Bathroom', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Hallway Garage', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    
    
    ['product_name' => 'Referral Partner Discount 10%', 'price' => 1, 'unit' => '0', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'Cash Deal no terms Discount', 'price' => 1, 'unit' => '0', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'Non Insurance Job Discount 20%', 'price' => 1, 'unit' => '0', 'product_category_id' => '8', 'product_description' => ''],
    
    ['product_name' => 'Guest Bedroom', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Hallway Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Fence', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Gutters', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Cleaning Mtl Tax', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Master Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'Walls Exterior', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => 'paint and seal (walls) includes labor and material'],
    ['product_name' => 'Guest Bedroom Closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => 'Texture, drywall, paint and seal [walls, ceiling] includes labor and materials'],
    ['product_name' => 'Comm Repr/Remod Tax', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    
    
   
   
    ['product_name' => 'Radiator unit - Detach & reset', 'price' => 508.07, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    
    ['product_name' => 'closet13', 'price' => 8, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'closet3', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'guest room 3', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'closet2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'guest room 2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'guest room1', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'closet 1', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'closet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'KITCHEN/LIVING', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => 'texture, drywall, paint [baseboards] sea and paint [walls]'],
    ['product_name' => 'PATIO', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'BATH TUB', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'shower', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'room4', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'family room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'STAIRS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'DINING ROOM2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'CLOSET4', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'GAME ROOM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'toilet', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    ['product_name' => 'LABOR MINIMUM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 7, 'product_description' => ''],
    
    ['product_name' => 'Cleaning Sales Tax', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    
    ['product_name' => 'TV ROOM DETACH AND RESET {LIGHT BAR-CROWN MOLDING}', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'LAUNDRY ROOM DETACH AND RESET {RECESSED LIGHT-HEAT/AC}', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'GARAGE DETACH AND RESET {CROWN MOLDING} REMOVE {RECESSED LIGHT FIXTURE} TEXTURE {DRYWALL-CEILING} SEAL {WALLS-CEILING} PAINT {WALLS-CEILING-CROWN MOLDING} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'KITCHEN DETACH AND RESET {RECESSED LIGHT-HEAT A/C} TEXTURE {DRYWALL-CEILING} PAINT AND SEAL {CEILING} INCLUDES LABOR AND MATERIAL', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'LIVING ROOM DETACH AND RESET {HEAT/AC-CEILING FAN} TEXTURE {DRYWALL-CEILING} SEAL AND PAINT {WALLS-CEILING} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'HALLWAY LIVING SEAL AND PAINT {WALLS-CEILING} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'STAIRS DETACH AND RESET {BASEBOARD} TEXTURE {CEILING} REMOVE {CARPET/PAD} PAINT AND SEAL {WALLS AND CEILING} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'CLOSET2 REMOVE {BASEBOARD-CARPET/PAD} SEAL {WALLS} PAINT {WALLS-BASEBOARD} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'ROOM 3 DETACH AND RESET {CEILING FAN-WINDOW BLIND-OUTLET/SWITCH-BASEBOARD} REMOVE {CARPET/PAD} TEXTURE {DRYWALL-CEILING} PAINT AND SEAL {WALLS-CEILING-BASEBOARD} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'CLOSET HALLWAY REMOVE {BASEBOARD-CARPET/PAD} SEAL AND PAINT {WALLS-BASEBOARD} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'GARAGE DETACH AND RESET {OVERHEAD DOOR OPENER-PORCELAIN LIGHT FIXTURE} TEXTURE {CEILING-DRYWALL} SEAL AND PAINT {CEILING} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'TOILETS SEAL AND PAINT {WALLS-CEILING} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'KITCHEN DETACH AND RESET {LIGHT FIXTURE} TEXTURE {DRYWALL-CEILING} SEAL AND PAINT {CEILING} LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'DINING ROOM SEAL AND PAINT {CEILING} DETACH AND RESET {CHANDALIER-HEAT/AC} TEXTURE {CEILING-DRYWALL} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'SUBROOM/STAIRS DETACH AND RESET {HEAT/AC} TEXTURE {DRYWALL-CEILING} PAINT AND SEAL {WALL-CEILING} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'LIVING ROOM DETACH AND RESET {LIGHT FIXTURE} SEAL AND PAINT {CEILING} TEXTURE {DRYWALL-CEILING} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'ENTRY/FOYER-SEAL AND PAINT {WALLS} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'FAMILY ROOM DETACH AND RESET {CEILING FAN-HEAT A/C-BASEBOARD} TEXTURE {DRYWALL-CEILING} SEAL AND PAINT {WALLS-CEILING-BASEBOARD} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'CLOSET1 REMOVE {BASEBOARD-CARPET/PAD} PAINT {WALLS-BASEBOARD} SEAL {WALLS} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'ROOM 1 DETACH AND RESET {CEILING FAN AND LIGHT-WINDOW DRAPERY} SEAL AND PAINT {CEILING} TEXTURE {CEILING} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'STUDY ROOM DETACH AND RESET {BASEBOARD} PAINT AND SEAL {WALLS AND CEILING} INCLUDING LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'ROOM2 DETACH AND RESET {CHANDALIER-HEAT/AC-WINDOW BLIND} TEXTURE {DRYWALL-CEILING} PAINT AND SEAL {WALLS-CEILING} INCLUDE LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'ROOM1 DETACH AND RESET {CEILING FAN-HEAT/AC-WINDOW DRAPERY-INTERIOR DOOR} REMOVE {WOOD DOOR FRAME} TEXTURE {DRYWALL} PAINT AND SEAL {WALLS-CEILING} LABOR AND MATERIAL INCLUDED', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'MASTER BATH REMOVE {LIGHT FIXTURE} PAINT AND SEAL {CEILING} TEXTURE {DRYWALL-CEILING} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'MASTER ROOM DETACH AND RESET {LIGHT FIXTURE-HEAT/AC-WINDOW BLIND-CEILING FAN} SEAL AND PAINT {CEILINGS} TEXTURE {CEILING-DRYWALL} PAINT {BASEBOARD} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'LAUNDRY ROOM DETACH AND RESET {WASHER-CLOSET ORGANIZER} SEAL AND PAINT {WALLS AND CEILING} TEXTURE {DRYWALL-CEILING} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'HALLWAY UPSTAIRS - DETACH AND RESET {BASEBOARD} REMOVE {CARPET/PAD} SEAL AND PAINT {CEILING-WALLS-BASEBOARD} INCLUDES LABOR AND MATERIALS', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'LAUNDRY ROOM- DETACH AND RESET (Baseboard, Washer, Dyer), REPAIR TILE FLOOR, SEAL AND PAINT WALLS INCLUDES: MATERIALS AND LABOR.', 'price' => 0, 'unit' => 'SQF', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'LIVING ROOM- DETACH AND RESET (Baseboard, Window Blinds) PAINT (Walls, Floor) SEAL WALLS, FLOOR PROTECTION, MASK WALL (Plastic, Paper, Tape) INCLUDES: MATERIALS AND LABOR.', 'price' => 0, 'unit' => 'SQF', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'HALLWAY- DETACH AND RESET {BASEBOARD} REMOVE {CARPET/PAD} PAINT AND SEAL {WALL-BASEBOARD} - INCLUDES: MATERIALS AND LABOR', 'price' => 0, 'unit' => 'SQF', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'DINING ROOM- DETACH AND RESET (Baseboard, Window Blinds), REPAIR TILE FLOOR, SEAL AND PAINT WALLS INCLUDES: MATERIALS AND LABOR.', 'price' => 0, 'unit' => 'SQF', 'product_category_id' => '8', 'product_description' => ''],
   
   
    ['product_name' => 'Roof Repairs', 'price' => 0, 'unit' => '1', 'product_category_id' => 7, 'product_description' => ''],
    
    ['product_name' => 'Living Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => 'texture, drywall, paint [ceiling] includes labor and materials'],
    ['product_name' => 'Bath tub', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => 'texture, drywall, seal and paint [walls] includes labor and materials'],
    ['product_name' => 'Master Bath', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => 'drywall, texture, ceiling, seal and paint [ceiling] paint [baseboard]  includes labor and materials'],
    ['product_name' => 'Living Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => 'texture, drywall, Paint [walls] Includes labor and materials'],
    ['product_name' => 'Kitchen', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => 'Seal and paint [walls] includes labor and materials'],
    ['product_name' => 'BATH ROOM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => 'TEXTURE, DRYWALL, SEAL AND PAINT [CEILING] INCLUDES LABOR AND MATERIALS'],
    ['product_name' => 'BED ROOM 2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => 'drywall, texture, seal and paint [ceiling] includes labor and materials'],
    ['product_name' => 'BED ROOM 1', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => 'drywall, texture, ceiling, seal and paint [ceiling] includes labor and materials'],
    ['product_name' => 'FENCING', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],
    ['product_name' => 'MAIN ROOF', 'price' => 0, 'unit' => 'EA', 'product_category_id' => '8', 'product_description' => ''],

  ['product_name' => 'BATHROOM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'SEAL AND PAINT TRIM, INCLUDES LABOR AND MATERIALS'],
  ['product_name' => 'OFFICE', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'SEAL AND PAINT TRIM, LABOR AND MATERIALS INCLUDED'],
  ['product_name' => 'MAIN LEVEL', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'INCLUDES LABOR AND MATERIALS'],
  ['product_name' => 'Kitchen', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'seal and paint the walls, labor and materials included.'],
  ['product_name' => 'ROOM 1', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'paint and seal [ceiling]'],
  ['product_name' => 'BEDROOM 2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, seal and paint [ceiling] includes labor and materials'],
  ['product_name' => 'BEDROOM 3', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, paint and seal [ceiling] includes labor and materials'],
  ['product_name' => 'Master Bathroom', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, seal [ceiling] paint [walls, crown molding, baseboard] includes labor and materials'],
  ['product_name' => 'Kitchen', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, paint [ceiling, crown molding] seal [ceiling] includes labor and materials'],
  ['product_name' => 'Living Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, seal [ceiling] paint [ceiling, crown molding] includes labor and materials'],
  ['product_name' => 'STAR ROOM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'texture, ceiling, seal and paint [ceiling] includes labor and materials'],
  ['product_name' => 'ENTRY-FOYER', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'seal and paint [CEILING] includes labor and materials'],
  ['product_name' => 'HALLWAY', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, seal and paint [ceiling] includes labor and materials'],
  ['product_name' => 'GARAGE', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, seal and paint [ceiling]'],
  ['product_name' => 'KITCHEN', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, paint and seal [ceiling] includes labor and materials'],
  ['product_name' => 'ENTRY/FOYER', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'seal and paint [walls] includes labor and materials'],
  ['product_name' => 'LAUNDRY ROOM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, paint and seal [ceiling] includes labor and materials'],
  ['product_name' => 'LIVING ROOM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, seal [ceiling, paneling] paint [ceiling, crown molding] includes labor and materials'],
  ['product_name' => 'ENTRY/FOYER', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'texture [ceiling] seal [ceiling, paneling] paint [crown molding, ceiling, paneling] includes labor and materials'],
  ['product_name' => 'ROOM2', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling'],
  ['product_name' => 'ROOM1', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, paint and seal [ceiling] includes labor and materials'],
  ['product_name' => 'ENTRY/FOYER', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, seal and paint [ceiling] includes labor and materials'],
  ['product_name' => 'THEATER ROOM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, seal and paint [ceiling] labor and materials'],
  ['product_name' => 'LIVING ROOM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'Drywall, texture, ceiling, paint and seal [ceiling] includes labor and materials.'],
  
  
  ['product_name' => 'Dining Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'Seal and Paint [Ceiling] Includes labor and materials'],
  
  ['product_name' => 'Living Room', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'Seal and Paint [walls] Includes labor and materials'],
  
  ['product_name' => 'TOILET INLET CONNECTION', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 1, 'product_description' => ''],
  ['product_name' => 'Additional Charge For High Roof (2 stories or greater)', 'price' => 0, 'unit' => 'SF', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Additional Charge For High Roof (2 stories or greater)', 'price' => 0, 'unit' => 'SQ', 'product_category_id' => 8, 'product_description' => ''],
  
  ['product_name' => 'SHINGLE ROOF AND METAL ROOF', 'price' => 0, 'unit' => 'SQ', 'product_category_id' => 8, 'product_description' => 'Remove and replace existing shingle and metal roof, Includes: Hourly labor rate for a roofer'],
  ['product_name' => 'REMOVE AND REPLACE', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'Interior door unit: Includes labor cost to remove a pre-hung interior door unit, hinges, jamb, stop, casing'],
  ['product_name' => 'REMOVE AND REPLACE', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'Bathtub, Includes labor cost to remove a Bathtub, drain set, and line water.'],
  ['product_name' => 'Remove and Replace', 'price' => 0, 'unit' => 'LF', 'product_category_id' => 8, 'product_description' => 'Cabinetry - upper (wall) Cabinets - lower (base) units Countertop - flat laid plastic or granite Include: Detach & Reset faucets and electrical items'],
  ['product_name' => 'KITCHEN', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, paint [ceiling, crown molding, paneling] seal [paneling, ceiling] includes labor and materials'],
  ['product_name' => 'Remove and Replace', 'price' => 0, 'unit' => 'SF', 'product_category_id' => 8, 'product_description' => 'Snaplock Laminate - simulated wood flooring'],
  ['product_name' => 'Remove and Replace', 'price' => 0, 'unit' => 'SF', 'product_category_id' => 8, 'product_description' => 'Drywall, texture, painting the ceiling or walls of affected areas'],
  ['product_name' => 'GUEST BATHROOM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'MASTER BATHROOM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, seal and paint [ceiling] includes labor and materials'],
  ['product_name' => 'MASTER BEDROOM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, includes labor and materials'],
  ['product_name' => 'DINING ROOM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, seal and paint [ceiling] includes labor and materials'],
  ['product_name' => 'MATERIAL SALES TAX', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'GENERALES', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'Permits, Taxes, insurance, permits & fees'],
  
  ['product_name' => 'SHINGLE ROOF', 'price' => 0, 'unit' => 'SQ', 'product_category_id' => 8, 'product_description' => 'Remove and replace existing roof, Includes: Hourly labor rate for a roofer.'],
  ['product_name' => 'METAL ROOF', 'price' => 0, 'unit' => 'SF', 'product_category_id' => 8, 'product_description' => 'Remove and replace existing roof, Includes: Hourly labor rate for a roofer.'],
  ['product_name' => 'WOOD FLOORING', 'price' => 0, 'unit' => 'SF', 'product_category_id' => 8, 'product_description' => 'Remove and replace existing Snaplock Laminate - simulated wood flooring'],
  ['product_name' => 'DRYWALL / TEXTURE / PAINT', 'price' => 0, 'unit' => 'SF', 'product_category_id' => 8, 'product_description' => 'Drywall, texture, painting the ceiling and walls of affected areas'],
  ['product_name' => 'SHEATHING - PLYWOOD - 5/8" CDX', 'price' => 0, 'unit' => 'SF', 'product_category_id' => 8, 'product_description' => 'Includes: Remove and replace 5/8" plywood, nails or staples, and installation labor.'],
  ['product_name' => 'ADDITIONAL TASKS', 'price' => 0, 'unit' => '1', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'SHINGLE ROOF', 'price' => 0, 'unit' => 'SQ', 'product_category_id' => 8, 'product_description' => 'Includes: Remove and replace existing composition shingles and felt Install new drip Edge, starter strip at roof perimeter and synthetic felt roofing underlayment to entire roof Surface, metal valleys and Install flashings as per local code Hourly labor rate for a roofer and permitting and administrative fees'],
  ['product_name' => 'MOLD REMEDIATION', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'Includes: Testing & lab analysis / Water Extraction & Remediation / Apply plant-based anti-microbial / Negative air fan/Air scrubber / Dehumidifier / Air mover (per 24 hour period) / Equipment decontamination charge per piece of equipment / General Laborer'],
  ['product_name' => 'Modified Bitumen Roof', 'price' => 0, 'unit' => 'SQ', 'product_category_id' => 8, 'product_description' => 'Remove and replace existing roof, Includes: Hourly labor rate for a roofer.'],
  ['product_name' => 'Post Mold Remediation Clearance Assessment (8 samples)', 'price' => 2375, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'ELECTRICAL Rewirewire - avg. residence boxes & wiring', 'price' => 0, 'unit' => 'SF', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'NOTE', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'The works will be carried out in the affected areas identified in the property inspection The detail of the calculations of the budgeted amounts are presented in the attached document'],
  ['product_name' => 'NOTE', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'These works will be carried out on the affected areas found in the inspection carried out on the property, and estimated according to the estimate presented.'],
  ['product_name' => 'Paint the ceiling', 'price' => 0, 'unit' => 'SF', 'product_category_id' => 8, 'product_description' => ''],

  ['product_name' => 'Toilet & Bath Accessories', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'BATHROOM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'Texture, drywall, paint and seal [walls, ceiling] includes labor and materials'],
  ['product_name' => 'MENS BATHROOM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'HALLWAY', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'drywall, texture, ceiling, paint and seal [ceiling] includes labor and materials'],
  ['product_name' => 'MAIN ROOM', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'ENTRANCE', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Drywall and Texture', 'price' => 0, 'unit' => 'SF', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Paint the walls and ceiling', 'price' => 0, 'unit' => 'SF', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Electrical (Smoke detector / Heat/AC register)', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Additional charge for high roof - 3 stories', 'price' => 0.34, 'unit' => 'SF', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Implements and tools for high roof - 3 stories', 'price' => 1927.91, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'Ladder 40 ft Scaffoldding (2 sets) Additional Roofers per hour Eye protection - plastic goggles - Disposable Fall protection harness and lanyard'],
  ['product_name' => 'Exterior Paint', 'price' => 0, 'unit' => 'SF', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Seal & Paint Trim', 'price' => 0, 'unit' => 'LF', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Stucco & Exterior Plaster', 'price' => 0, 'unit' => 'SF', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Exterior Door', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Windows Single Hung 13-19 sf', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Windows Single Hung 20-28', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Material Sales Tax', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'GENERALS', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Permits, Taxes, insurance, permits & fees'],
  ['product_name' => 'MENS BATHROOM', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Electrical Doors Toilet and Bath Accesories Painting Plumbing Cabinetry Drywall and Texture'],
  ['product_name' => 'WOMENS BATHROOM', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Electrical Doors Toilet and Bath Accesories Painting Plumbing Cabinetry Drywall and Texture'],
  ['product_name' => 'MAIN BATHROOM', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Toilet & Bath Accesories Electrical Plumbing Doors Cabinetry Painting Drywall and Texture'],
  ['product_name' => 'HALLWAY', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Electrical Doors Painting Drywall and Texture'],
  ['product_name' => 'MAIN ROOM', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Electrical Doors Painting Drywall and Texture'],
  ['product_name' => 'ENTRANCE', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Electrical Doors Painting Drywall and Texture'],
  ['product_name' => 'Exterior', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Mold testing one time only each (Up to 5 samples including one outside) at front', 'price' => 700, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Mold testing one time only each (Up to 8 samples including one outside) at front', 'price' => 1000, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Mold testing one time only each (Up to 8 samples including one outside) at front', 'price' => 1000, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Moisture Assessment', 'price' => 1000, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Demolition and Build Back', 'price' => 3300, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Includes Texture and Fixtures'],
  ['product_name' => 'Roof Replacement', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Door Replace and Install', 'price' => 700, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Includes labor and material'],
  ['product_name' => 'Bathroom Remodel', 'price' => 9200, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Includes Dumpster Includes Plumbing, Shower Pan, Replace Walls, Includes Ceramic Tiles, Vanity, Mirror, Lights, Toilet, Extraction System and Glass doors'],
  ['product_name' => 'Demolition Walls and Kitchen in Hallway. Drywall Repairs in Ceiling and Walls', 'price' => 3300, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Includes Texture and Fixtures'],
  ['product_name' => 'Painting, Ceiling and Walls', 'price' => 5300, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Includes Labor & Materials'],
  ['product_name' => 'Baseboard Replace', 'price' => 10, 'unit' => 'LF', 'product_category_id' => 8, 'product_description' => 'Includes Labor & Material'],
  ['product_name' => 'Vinyl Plank Flooring', 'price' => 5.99, 'unit' => 'SQF', 'product_category_id' => 8, 'product_description' => 'Includes Labor & Material'],
  ['product_name' => 'Warranty of 5 Years of Labor', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'AcquaSafe Water Softener System Total Whole House', 'price' => 8500, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Labor Only', 'price' => 400, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Residential Supervision / Project Management'],
  ['product_name' => 'Electrical', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Installation Labor Outlets / Microwave Oven'],
  ['product_name' => 'Plumbing', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Installation labor Sink - double basin / Sink faucet / P-trap assembly'],
  ['product_name' => 'Floor Covering', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Installation labor vinyl tile'],
  ['product_name' => 'Finish Carpentry / Trimwork', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Installation Labor Baseboard'],
  ['product_name' => 'Cabinetry / Countertop (Supply and Installation)', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Supply and installation Cabinetry High Quality / Countertop Quarzo Himalaya Add-on for mitered corner (Countertop) / Installation Backsplash'],
  ['product_name' => 'Drywall / Texture / Paint', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Paint and Texture drywall the walls'],
  ['product_name' => 'General Demolition', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Cabinetry - upper (wall) units / Cabinetry - lower (base) units Carpet and Baseboard / General clean-up'],
  ['product_name' => 'Based on Xactimate Estimate', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Ceiling and Walls Texture and Painting', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Based in Attached Proposal'],
  ['product_name' => 'Roof Replacement', 'price' => 0, 'unit' => 'UND', 'product_category_id' => 8, 'product_description' => 'Based Attached Proposal'],
  ['product_name' => 'Post Mold Remediation Clearance Assessment (7 samples)', 'price' => 2225, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Post Mold Remediation Clearance Assessment (6 samples)', 'price' => 2075, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Post Mold Remediation Clearance Assessment (5 samples)', 'price' => 1925, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Post Mold Remediation Clearance Assessment (4 samples)', 'price' => 1775, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Post Mold Remediation Clearance Assessment (3 samples)', 'price' => 1625, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Post Mold Remediation Clearance Assessment (2 samples)', 'price' => 1475, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],

  ['product_name' => 'Water Damage', 'price' => 11000, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => 'Removal of flooring and baseboard. Includes dry out. 2103.25 SQF'],
  ['product_name' => 'Weathered wood Shingle', 'price' => 0, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Shakewood Shingle', 'price' => 0, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Hickory Shingle', 'price' => 0, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Barkwood Shingle', 'price' => 0, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'R&R Tarp - poly - per sq ft (lab & mat)', 'price' => 1.5, 'unit' => 'SQF', 'product_category_id' => 8, 'product_description' => 'Allowance for tarping the back slope by the contractor.'],
  ['product_name' => '2 x 4 Wood', 'price' => 0, 'unit' => 'LF', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Plywood Board 4 x 8', 'price' => 0, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => 'Tear Old Plywood Board and Install New Board'],
  ['product_name' => 'Ashpalt Shingle Roofing Installation Equipment Allowance', 'price' => 0, 'unit' => 'SQ', 'product_category_id' => 8, 'product_description' => 'Job related costs of specialty equipment used for job quality and efficiency, including: Roof jacks, pneumatic roofing nailer, shingle cutting tools. Daily rental. Consumables extra.'],
  ['product_name' => 'Ashpalt Shingle Roofing Installation Job Supplies', 'price' => 0, 'unit' => 'SQ', 'product_category_id' => 8, 'product_description' => 'Cost of related materials and supplies typically required to install asphalt shingle roof including: fasteners, underlayment, drip edges, sealant and basic flashing.'],
  ['product_name' => 'Architectural Shingle Roofing Installation Labor, Basic', 'price' => 0, 'unit' => 'SQ', 'product_category_id' => 8, 'product_description' => 'Basic labor to install asphalt shingle roof with favorable site conditions. Install drip edge/eave trim, and valley flashing. Install roofing paper / membrane. Layout, fabricate, overlap and secure asphalt shingles per manufacturer instructions. Includes planning, equipment and material acquisition, area preparation and protection, setup and cleanup.'],
  ['product_name' => 'Asphalt Shingle Roof Cost', 'price' => 0, 'unit' => 'SQ', 'product_category_id' => 8, 'product_description' => 'Non-discounted retail pricing for: Asphalt composition shingle. 2.2 lbs per SF. UL Class A fire resistance and 110 mph wind resistance. 30 yr warranty. Quantity includes typical waste overage, material for repair and local delivery.'],
  ['product_name' => 'Asphalt Shingle Roof Debris Disposal', 'price' => 0, 'unit' => 'SQ', 'product_category_id' => 8, 'product_description' => 'Costs to load and haul away old materials, installation waste and associated debris.'],
  ['product_name' => 'Tear Off Roof', 'price' => 0, 'unit' => 'SQ', 'product_category_id' => 8, 'product_description' => 'Remove existing roofing material, roof paper, vent jacks and flashing, and gutters if needed. Sweep area clean of all nails / staples.'],
  ['product_name' => 'WRITTEN TECHNICAL REPORT', 'price' => 650, 'unit' => 'UNIT', 'product_category_id' => 7, 'product_description' => ''],
  ['product_name' => 'FIELD LICENSED MOLD ASSESSOR', 'price' => 200, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'AIR-O-CELL & SWAB ANALYSIS', 'price' => 450, 'unit' => 'UNIT', 'product_category_id' => 7, 'product_description' => ''],
  ['product_name' => 'Visual Inspection', 'price' => 350, 'unit' => 'UNIT', 'product_category_id' => 7, 'product_description' => ''],
  ['product_name' => 'Royalty Fee per services rendered Year 2021', 'price' => 1, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Dedicated project management', 'price' => 0, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Includes permitting and administrative fees', 'price' => 0, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Includes all labor required to complete the job', 'price' => 0, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Install premium GAF timberline HD ultra shingles', 'price' => 0, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Install flashings as per local code', 'price' => 0, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Install metal valleys', 'price' => 0, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Install 3ft of ice and water shield at eaves, valleys and penetrations', 'price' => 0, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Install synthetic felt roofing underlayment to entire roof surface', 'price' => 0, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Install starter strip at roof perimeter', 'price' => 0, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => 8],
  ['product_name' => 'Install new drip edge at roof perimeter', 'price' => 0, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => 8],
  ['product_name' => 'Remove and dispose of existing roof', 'price' => 0, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Emergency tarp installation on the roof under extreme weather conditions', 'price' => 4800, 'unit' => 'EA', 'product_category_id' => 8, 'product_description' => '1. Emergency tarp installation on the roof under extreme weather conditions in the above address.  2. Emergency services call/mobilization to job site. 3. Labor (ladderman installer hauler)  4. Affected area detection/setup.  5. Materials (Tarps, Shims 8 in, Nails 1ft 1/4 in, Ropes)'],
  ['product_name' => 'Hose Bag for Injector Cabinet', 'price' => 300, 'unit' => 'Unit', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Injector Cabinet', 'price' => 500, 'unit' => 'Unit', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Air Mover', 'price' => 150, 'unit' => 'Unit', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Air Scrubber DriEaz', 'price' => 1000, 'unit' => 'Unit', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Dehumidifier Dryeaz', 'price' => 2000, 'unit' => 'Unit', 'product_category_id' => 8, 'product_description' => ''],
  ['product_name' => 'Hydroxyl generator - odor counteractant - 2 optics', 'price' => 300, 'unit' => 'UNIT', 'product_category_id' => 8, 'product_description' => ''],

    ['product_name' => 'Deodorize building - Hot thermal fog Labor', 'price' => 500, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'HEPA Vacuuming - Detailed', 'price' => 0.3, 'unit' => 'SF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Apply biological cleaning agent (spore-based) to more than the walls and ceiling', 'price' => 0.1, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Seal stud wall for odor control', 'price' => 0.25, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Clean floor or roof joist system - Heavy', 'price' => 0.3, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Tear out drywall, cleanup, bag - Cat 3 Labor', 'price' => 250, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Dumpster load - Approx. 12 yards, 1-3 tons of debris', 'price' => 350, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Generator - 10-30KW (per day - 24 hour) - no monitoring', 'price' => 400, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Remove Outlet or switch cover 1 Labor', 'price' => 80, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Hazardous Waste/Mold Cleaning- Supervisory/Admin- PER HOUR', 'price' => 70, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Hazardous Waste/Mold Cleaning Technician - per hour', 'price' => 35, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Respirator cartridge - HEPA & vapor & gas (per pair)', 'price' => 37.7, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Respirator - Full face - multi-purpose resp. (per day)', 'price' => 7.61, 'unit' => 'DAY', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Fire mitigation emergency svc call - during business hours', 'price' => 145.81, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Air handler - with A-coil - Detach & reset', 'price' => 995, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Discounts', 'price' => 0, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Profit', 'price' => 0, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Overhead', 'price' => 0, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Fall protection harness and lanyard - per day', 'price' => 10, 'unit' => 'DAY', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Boom Lift - 50 ft Reach - Electric Powered', 'price' => 695, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => '12 mil Fire Retardant Structural Wrap Heat Shrink Seal', 'price' => 3.5, 'unit' => 'SF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'MRE', 'price' => 0, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'R & R Tarp all purpose-poly set price (labor) boom leaf sup', 'price' => 2000, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Bio-wash wall, floors, ceilings large room (fogging)', 'price' => 300, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Administrative Mortgage Endorsement (Check Processing) - MR', 'price' => 500, 'unit' => 'ITEM', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Negative Air Fan / Air Scrubber (24 hr period) - MR', 'price' => 175, 'unit' => 'DA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Dehumidifier (per 24 hour period) Large - No monitoring - MR', 'price' => 190, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Air Mover (per 24 hour period) No monitoring - MR', 'price' => 55, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Demo and clean-up labor per hours', 'price' => 65, 'unit' => 'HR', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Wrapping Box (Medium) Per Box', 'price' => 40, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Manipulation per Trip. Local', 'price' => 125, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Air Scrubber - Anti-Microbial Internal Filter', 'price' => 200, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'HEPA filter for HEPA VAC', 'price' => 50, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Tyveck Disp. Suit P/Day - P/Tech', 'price' => 20, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Full face mask - W / Hepa', 'price' => 16, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Mold testing one time only each (Up to 5 samples including one outside) at front', 'price' => 700, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Hepa Vac / Hr', 'price' => 65, 'unit' => 'HR', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Sand & Paint studs /Hr', 'price' => 65, 'unit' => 'HR', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Gloves', 'price' => 10, 'unit' => 'PCS', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Post rem. Breakdown and equip. Clean-up per hour', 'price' => 65, 'unit' => 'HR', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Hauling and dump fees per pick-up size load', 'price' => 185, 'unit' => 'UNIT', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Pre-filters for Air Scrubber and Dehumidifier Each', 'price' => 20, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    
    ['product_name' => 'Application of biocide spray per room (Microbian)', 'price' => 15, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Bag debris for disposal per bag', 'price' => 7, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Furniture Manipulation / Protection Per Hour', 'price' => 65, 'unit' => 'HR', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Dry Wall Removal', 'price' => 4.88, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Water Extraction Remediation Hours Technician', 'price' => 38, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Moisture Mapping (Per Room)', 'price' => 20, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Service Call / Mobilization', 'price' => 150, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Gas Power Generator (Gas Included)', 'price' => 150, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Removal of Tile', 'price' => 10.84, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'General Clean Up', 'price' => 0.28, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Ozone Machine', 'price' => 180, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => '1st. Stage Filter', 'price' => 2, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Carbon Filter', 'price' => 2, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Deodorize', 'price' => 0.28, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Thermal Fog', 'price' => 0.28, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Ceiling', 'price' => 0.28, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Walls', 'price' => 0.28, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],

    ['product_name' => 'Administrative Mortgage Endorsement (Optional)', 'price' => 750, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Floor', 'price' => 0.28, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Water Extraction from hard surface floor', 'price' => 0.26, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Add for dehumidifier filter', 'price' => 102.35, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Thermal Imaging Service', 'price' => 250, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Content Manipulation Charge - per hour', 'price' => 52.65, 'unit' => 'HR', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Water Extraction & Remediation Technician - per hour - after hours', 'price' => 76.35, 'unit' => 'HR', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Water Extraction & Remediation Technician - per hour', 'price' => 50.85, 'unit' => 'HR', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Protect - Cover with plastic', 'price' => 0.33, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Drill holes for wall cavity drying', 'price' => 0.65, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'HEPA Vacuuming - Light - (PER SF)', 'price' => 0.95, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Apply anti-microbial agent to {V}', 'price' => 0.37, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Equipment setup, take down, and monitoring (hourly charge) - after hours', 'price' => 76.35, 'unit' => 'HR', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Equipment setup, take down, and monitoring (hourly charge)', 'price' => 50.85, 'unit' => 'HR', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Peel & seal zipper - heavy duty - after business hours', 'price' => 15.46, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Containment Barrier - tension post - per day', 'price' => 3.3, 'unit' => 'DAY', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Remove polyethylene vapor barrier', 'price' => 0.1, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Containment Barrier/Airlock/Decon. Chamber', 'price' => 1.01, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Equipment decontamination charge - per piece of equipment', 'price' => 69, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Tear out and bag wet insulation', 'price' => 1.6, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Tear out non-salv. vinyl tile, cut & bag', 'price' => 3.04, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Tear out wet non-salv. gluedn. cpt, cut/bag', 'price' => 1.87, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Tear out wet non-salvage cpt, cut/bag', 'price' => 1.27, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Tear out wet drywall, no bagging', 'price' => 1.29, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Tear out non-salv solid/eng. wood flr & bag -', 'price' => 4.48, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Tear out non-salv floating floor & bag', 'price' => 2.32, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Interior door slab only - Detach', 'price' => 8.15, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Countertop - solid surface/granite - Detach', 'price' => 10.76, 'unit' => 'LF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Countertop - flat laid plastic lam. - Detach', 'price' => 8.08, 'unit' => 'LF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Cabinet - vanity unit - Detach', 'price' => 21.37, 'unit' => 'LF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Cabinet - lower (base) unit - Detach', 'price' => 24.9, 'unit' => 'LF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Cabinet - full height unit - Detach', 'price' => 24.9, 'unit' => 'LF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Tear out baseboard', 'price' => 2.3, 'unit' => 'LF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Remove wet ceiling tile & drywall and bag', 'price' => 1.48, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Plastic bag - used for disposal of contaminated items', 'price' => 3.38, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Block and pad furniture in room - Large amount', 'price' => 86.65, 'unit' => 'ROOM', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Range - freestanding - electric - Detach', 'price' => 36.21, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Dishwasher - Detach', 'price' => 82.03, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Dryer - electric - Detach', 'price' => 27.15, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Washing machine - Detach', 'price' => 30.15, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Refrigerator - Detach', 'price' => 36.21, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Emergency service call - during business hours', 'price' => 145.34, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Add for personal protective equipment - Heavy duty', 'price' => 18.82, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Add for personal protective equipment (hazardous cleanup)', 'price' => 8.55, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Personal protective gloves - Heavy duty (per pair) G40', 'price' => 4.71, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Boots - waterproof latex - Disposable (per pair)', 'price' => 7.17, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Eye protection - Plastic Goggles - Disposable', 'price' => 4.76, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Emergency tarp removal and re-installation services', 'price' => 4800, 'unit' => 'EA', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Tarp - poly - per sq ft (lab & mat)', 'price' => 2.55, 'unit' => 'SQF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Ducting - flexible - 6" round', 'price' => 1.42, 'unit' => 'LF', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Wood floor drying extraction mat (per 24 hr prd) No monit.', 'price' => 180, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Power distribution box', 'price' => 36.87, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Add for HEPA filter (for negative air exhaust fan)', 'price' => 225, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Negative air fan/Air scrubber (24 hr period) - No monit.', 'price' => 175, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Wall cavity drying-Inj. type (per 24 hr period) No monit.', 'price' => 180, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Axial fan air mover - 1 HP (per 24 hr period)-No monit.', 'price' => 38, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Air mover (per 24 hour period) - No monitoring', 'price' => 55, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Dehumidifier (per 24 hour period) XXLarge - No monitoring', 'price' => 190, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Dehumidifier (per 24 hour period) XLarge - No monitoring', 'price' => 190, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Dehumidifier (per 24 hour period) Large - No monitoring', 'price' => 190, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'Dehumidifier (per 24 hour period) - No monitoring', 'price' => 190, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
    ['product_name' => 'WRT GENERAL SERVICES', 'price' => 0, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8],
      ['product_name' => 'ADD FOR HEPA FILTER (FOR NEGATIVE AIR EXHAUST FAN)', 'price' => 225, 'unit' => 'UND', 'product_description' => '', 'product_category_id' => 8]   



];

    foreach ($products as $product) {
        Product::create([
            'uuid' => Uuid::uuid4()->toString(),
            'product_category_id' => $product['product_category_id'],
            'product_name' => $product['product_name'],
            'product_description' => $product['product_description'],
            'price' => $product['price'],
            'unit' => $product['unit'],
        ]);
    }
}
}
