FROM php:8.2-fpm

# Instalar dependencias
RUN apt-get update && apt-get install -y \
    cron \
    libzip-dev \
    zip \
    unzip \
    git \
    curl

# Instalar extensiones PHP
RUN docker-php-ext-install pdo pdo_mysql zip

# Configurar crontab
COPY crontab.docker /etc/cron.d/laravel-cron
RUN chmod 0644 /etc/cron.d/laravel-cron
RUN crontab /etc/cron.d/laravel-cron

# Directorio de trabajo
WORKDIR /var/www/html

# Comando para iniciar cron en primer plano
CMD ["cron", "-f"] 