# Nixpacks Configuration for Railway Laravel Deployment
# Alternative to Dockerfile - Railway's preferred method

[phases.build]
nixPkgs = ["nodejs", "npm", "php84", "php84Packages.composer"]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
# These will be set in Railway dashboard
APP_ENV = "production"
APP_DEBUG = "false"
NODE_ENV = "production"

[providers.php]
version = "8.4"

[providers.node]
version = "20"
