[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.production"

[deploy]
startCommand = "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"

[[services]]
name = "laravel-app"

[[services]]
name = "redis"
image = "redis:7-alpine"